/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.awt.*;

public class Intructions extends JPanel {
    public Intructions() {
        initializeUI();
    }

    private void initializeUI() {
        this.setLayout(new BorderLayout());
        this.setPreferredSize(new Dimension(460, 310));

        JTextArea textArea = new JTextArea(10, 40);
        String intra = "\"Attributes\"\n" + "    Format: attribute names separated by comma.\n";
        intra += "    Examples:\n" + "	name,location,favAppl,appl,provider\n" + "	 A,B,C,D,E\n";
        intra += "\n" + "\"Functional Dependencies\"\n" +"    Format:\n" + "	Attribute names separated by comma and contained in { }.\n";
        intra += "	FD's separated by semicolon.\n" + "    Examples:\n" +"	{name}->{location,favAppl};{appl}->{provider} \n";
        intra += "	{A}->{B,C};{C,D}->{E};{E}->{A};{B}->{D}\n";
        intra += "\nClick on Print Relation to view the entered Relation.";
        intra += "\nClick on Decompose to view the decomposed relations." + "\nClick on Restart to clear session." + "\n\n*Case-Insensitive.*";
        textArea.setText(intra);

        // By default the JTextArea is editable, calling
        // setEditable(false) produce uneditable JTextArea.
        textArea.setEditable(false);
        //JScrollPane scrollPane = new JScrollPane(textArea);
        JScrollPane scrollPane =new JScrollPane(textArea);
        this.add(scrollPane, BorderLayout.CENTER);
    }

    public static void showFrame() {
        JPanel panel = new Intructions();
        panel.setOpaque(true);

        JFrame frame = new JFrame("Intructions");
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        frame.setContentPane(panel);
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                Intructions.showFrame();
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
