package dbms_proj;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.util.StringTokenizer;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Amogh saxena
 */
public class NewJFrame extends javax.swing.JFrame {
    
    public String name;
    public String attributes;
    public String fds;
    public Vector<String> attri;
    public Vector<String> fun;
    public String attr;
    public String funs;
    public int hua_kya=0;
    public Relation r;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        this.setTitle("Normalization Solver: Module 1");
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        PANDU.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button6 = new java.awt.Button();
        Decompose = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        PANDU = new java.awt.TextArea();
        Fds = new java.awt.TextField();
        label1 = new java.awt.Label();
        Attr = new java.awt.TextField();
        label2 = new java.awt.Label();
        NameRe = new java.awt.TextField();
        ShowAllKeys = new java.awt.Button();
        rest = new java.awt.Button();
        label3 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button5 = new java.awt.Button();
        result_Here = new java.awt.TextArea();

        button6.setBackground(new java.awt.Color(204, 204, 204));
        button6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button6.setLabel("Submit");
        button6.setName(""); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(51, 51, 51));

        Decompose.setActionCommand("Decompose");
        Decompose.setBackground(new java.awt.Color(204, 204, 204));
        Decompose.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Decompose.setLabel("Decompose");
        Decompose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DecomposeMouseClicked(evt);
            }
        });
        Decompose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecomposeActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(204, 204, 204));
        button3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button3.setLabel("Instructions");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(204, 204, 204));
        button4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button4.setLabel("About Team");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        PANDU.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        Fds.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(102, 102, 102));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("FD's :");

        Attr.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Attr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttrMouseClicked(evt);
            }
        });
        Attr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AttrFocusGained(evt);
            }
        });
        Attr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttrActionPerformed(evt);
            }
        });

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(102, 102, 102));
        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Name of Relation :");

        NameRe.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NameRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameReActionPerformed(evt);
            }
        });

        ShowAllKeys.setBackground(new java.awt.Color(204, 204, 204));
        ShowAllKeys.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ShowAllKeys.setLabel("Print Relation");
        ShowAllKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllKeysActionPerformed(evt);
            }
        });

        rest.setBackground(new java.awt.Color(204, 204, 204));
        rest.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rest.setLabel("Restart");
        rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restActionPerformed(evt);
            }
        });

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(102, 102, 102));
        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Attributes :");

        button1.setActionCommand("c1");
        button1.setBackground(new java.awt.Color(204, 204, 204));
        button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button1.setLabel("Clear");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setActionCommand("c2");
        button2.setBackground(new java.awt.Color(204, 204, 204));
        button2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button2.setLabel("Clear");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button5.setActionCommand("c3");
        button5.setBackground(new java.awt.Color(204, 204, 204));
        button5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button5.setLabel("Clear");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Attr, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fds, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NameRe, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(result_Here, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ShowAllKeys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Decompose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(rest, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PANDU, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NameRe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Attr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(Fds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowAllKeys, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(Decompose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result_Here, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(PANDU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttrMouseClicked
    }//GEN-LAST:event_AttrMouseClicked

    private void AttrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttrActionPerformed
    }//GEN-LAST:event_AttrActionPerformed

    public Boolean checkValid(String name,String attr,String fd)
    {
        if(name.length()==0||attr.length()==0||fd.length()==0)
            return false;
        return true;
    }
    private void AttrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AttrFocusGained
    }//GEN-LAST:event_AttrFocusGained

    private void restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restActionPerformed
        String yee=PANDU.getText();
        PANDU.setText("");
        name=NameRe.getText().toUpperCase();
        attributes=Attr.getText().toUpperCase();
        fds=Fds.getText().toUpperCase();
        String noo=result_Here.getText();
        result_Here.setText("");
        NameRe.setText("");
        Attr.setText("");
        Fds.setText("");
        hua_kya=0;
        Relation.cnt=0;
    }//GEN-LAST:event_restActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       name=NameRe.getText().toUpperCase();
       NameRe.setText("");
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        attributes=Attr.getText().toUpperCase();
        Attr.setText("");
    }//GEN-LAST:event_button2ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        fds=Fds.getText().toUpperCase();
        Fds.setText("");
    }//GEN-LAST:event_button5ActionPerformed

    private void DecomposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecomposeActionPerformed

        name=NameRe.getText();
        attributes=Attr.getText();
        fds=Fds.getText();
        if(!checkValid(name,attributes,fds))
            PANDU.setText("Error!Please Enter All Values First.");
        else
        {
            ShowAllKeysActionPerformed(evt);
            if(r!=null)
            {
                if(r.NF==4)
                {
                    PANDU.setText("Relation is already in BCNF.");
                    hua_kya=0;
                }
                else
                {
                    r.decomposeRel();
                    int siz=r.decomposed.size();
                    String answer="";
                    for(int i=0;i<siz;i++)
                    {
                        if(i!=0)
                        answer+="\n";
                        answer+=r.decomposed.elementAt(i);
                        answer+="*******************************";
                    }
                    PANDU.setText(answer);
                    hua_kya=0;
                }
            }
        }
    }//GEN-LAST:event_DecomposeActionPerformed

    private void DecomposeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecomposeMouseClicked

    }//GEN-LAST:event_DecomposeMouseClicked

    private void NameReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameReActionPerformed
    }//GEN-LAST:event_NameReActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        new Abouts().showFrame();
    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        new Intructions().showFrame();
    }//GEN-LAST:event_button3ActionPerformed

    private void ShowAllKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllKeysActionPerformed
        String hi=PANDU.getText();
        PANDU.setText("");
        name=NameRe.getText().toUpperCase();
        attributes=Attr.getText().toUpperCase();
        fds=Fds.getText().toUpperCase();
        if(!checkValid(name,attributes,fds))
        result_Here.setText("Error!Please Enter All Values First.");
        else
        {
            boolean flag=false;
            attri= new Vector<String>();
            fun= new Vector<String>();
            attr= new String();
            funs=new String();
            StringTokenizer st = new StringTokenizer(attributes,",");
            while(st.hasMoreTokens())
            {
                attr=st.nextToken();
                attri.add(attr);
            }
            StringTokenizer st1 = new StringTokenizer(fds,";");
            while(st1.hasMoreTokens())
            {
                funs=st1.nextToken();
                fun.add(funs);
            }
            while(flag==false)
            {
                try
                {
                    r=new Relation(this);
                    flag=true;
                    hua_kya=1;
                    result_Here.setText(r.toString());
                }
                catch (InvalidAttributeException iae) {
                    result_Here.setText("Please re-enter the proper functional dependency and continue.");
                    Fds.setText("");
                    break;
                }
                catch(InvalidFunctionalDependencyException ifde) {
                    Fds.setText("");
                    result_Here.setText("Please re-enter the proper functional dependency and continue.");
                    break;
                }

            }
        }
    }//GEN-LAST:event_ShowAllKeysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Attr;
    private java.awt.Button Decompose;
    private java.awt.TextField Fds;
    private java.awt.TextField NameRe;
    private java.awt.TextArea PANDU;
    private java.awt.Button ShowAllKeys;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Button rest;
    private java.awt.TextArea result_Here;
    // End of variables declaration//GEN-END:variables
}
