package dbms_proj;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.util.StringTokenizer;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Amogh saxena
 */
public class NewJFrame extends javax.swing.JFrame {
    
    public String name;
    public String attributes;
    public String fds;
    public Vector<String> attri;
    public Vector<String> fun;
    public String attr;
    public String funs;
    public int hua_kya=0;
    public Relation r;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        //this.setBackground(Color.BLACK);
        this.setTitle("Normalization Solver");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button6 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        Decompose = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        result_Here = new java.awt.TextArea();
        Fds = new java.awt.TextField();
        label1 = new java.awt.Label();
        Attr = new java.awt.TextField();
        label2 = new java.awt.Label();
        NameRe = new java.awt.TextField();
        ShowAllKeys = new java.awt.Button();
        rest = new java.awt.Button();

        button6.setBackground(new java.awt.Color(204, 204, 204));
        button6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button6.setLabel("Submit");
        button6.setName(""); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Attributes :");

        Decompose.setActionCommand("Decompose");
        Decompose.setBackground(new java.awt.Color(204, 204, 204));
        Decompose.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Decompose.setLabel("Decompose");
        Decompose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DecomposeMouseClicked(evt);
            }
        });
        Decompose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecomposeActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(204, 204, 204));
        button3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button3.setLabel("Instructions");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(204, 204, 204));
        button4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button4.setLabel("About");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        result_Here.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("FD's :");

        Attr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttrMouseClicked(evt);
            }
        });
        Attr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AttrFocusGained(evt);
            }
        });
        Attr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttrActionPerformed(evt);
            }
        });

        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText("Name of Relation :");

        ShowAllKeys.setBackground(new java.awt.Color(204, 204, 204));
        ShowAllKeys.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ShowAllKeys.setLabel("Solve");
        ShowAllKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllKeysActionPerformed(evt);
            }
        });

        rest.setBackground(new java.awt.Color(204, 204, 204));
        rest.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rest.setLabel("Restart");
        rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ShowAllKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Decompose, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(rest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addGap(159, 159, 159)
                        .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(NameRe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Attr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(result_Here, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameRe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Attr, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(Fds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ShowAllKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Decompose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(rest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(result_Here, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AttrMouseClicked

    private void DecomposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecomposeActionPerformed

        // TODO add your handling code here:
        name=NameRe.getText();
        attributes=Attr.getText();
        fds=Fds.getText();
        if(!checkValid(name,attributes,fds))
            result_Here.setText("Error!Please Enter All Values First.");
        else if(hua_kya==0)
            result_Here.setText("First click on solve");
        else
        {
            r.decomposeRel();
            int siz=r.decomposed.size();
            String answer="";
            for(int i=0;i<siz;i++)
            {
                if(i!=0)
                    answer+="\n";
                answer+=r.decomposed.elementAt(i);
            }
            result_Here.setText(answer);
            //Decompose.setEnabled(false);
        }
    }//GEN-LAST:event_DecomposeActionPerformed

    private void DecomposeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecomposeMouseClicked


        // TODO add your handling code here:
    }//GEN-LAST:event_DecomposeMouseClicked

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        //new Help().setVisible(true);
        new Intructions().showFrame();
        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void AttrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AttrActionPerformed

    public Boolean checkValid(String name,String attr,String fd)
    {
        if(name.length()==0||attr.length()==0||fd.length()==0)
            return false;
        return true;
    }
    private void ShowAllKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllKeysActionPerformed
        
        name=NameRe.getText().toUpperCase();
        attributes=Attr.getText().toUpperCase();
        fds=Fds.getText().toUpperCase();
        if(!checkValid(name,attributes,fds))
            result_Here.setText("Error!Please Enter All Values First.");
        else
        {
            boolean flag=false;
            attri= new Vector<String>();
            fun= new Vector<String>();
            attr= new String();
            funs=new String();
            StringTokenizer st = new StringTokenizer(attributes,",");
            while(st.hasMoreTokens())
            {
                attr=st.nextToken();
                attri.add(attr);
            }
            StringTokenizer st1 = new StringTokenizer(fds,";");
            while(st1.hasMoreTokens())
            {
                funs=st1.nextToken();
                fun.add(funs);
            }
            while(flag==false)
            {
                try
                {
                    r=new Relation(this);
                    flag=true;
                    hua_kya=1;
                    result_Here.setText(r.toString());
                }
                catch (InvalidAttributeException iae) {
                    result_Here.setText("Please re-enter the proper functional dependency and continue:");
                    Fds.setText("");
                    break;
                } 
                catch(InvalidFunctionalDependencyException ifde) {
                    Fds.setText("");
                    result_Here.setText("Please re-enter the proper functional dependency and continue:");
                    break;
                }
                
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowAllKeysActionPerformed

    private void AttrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AttrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_AttrFocusGained

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        new Abouts().showFrame();
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restActionPerformed
        // TODO add your handling code here:
        NameRe.setText("");
        Attr.setText("");
        Fds.setText("");
        result_Here.setText("");
        Decompose.setEnabled(true);
    }//GEN-LAST:event_restActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Attr;
    private java.awt.Button Decompose;
    private java.awt.TextField Fds;
    private java.awt.TextField NameRe;
    private java.awt.Button ShowAllKeys;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button6;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Button rest;
    private java.awt.TextArea result_Here;
    // End of variables declaration//GEN-END:variables
}
