
import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Radhesh Sarma
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    Directory d;
    int globaldepth,bfr;
    boolean b1=false,d1=false;
  HashSet<Integer> store = new HashSet<Integer>(); 
    public GUI() {
        initComponents();
         //this.setExtendedState(MAXIMIZED_BOTH);
         setSize(1100,850);
         
       Object[] cname={"Directory Number","Bucket ID","Local Depth" ,"Content of Bucket pointed by it",};
            DefaultTableModel model=new DefaultTableModel(cname,16);
            table.setModel(model);
             
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userinput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Insert = new javax.swing.JButton();
        search_box_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        global_depth = new javax.swing.JTextField();
        gd_input = new javax.swing.JButton();
        BFR = new javax.swing.JButton();
        bfr_input = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        user_input1 = new javax.swing.JTextField();
        clear1 = new javax.swing.JButton();
        clear2 = new javax.swing.JButton();
        clear4 = new javax.swing.JButton();
        clear3 = new javax.swing.JButton();
        Restart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userinput.setBackground(new java.awt.Color(36, 47, 65));
        userinput.setPreferredSize(new java.awt.Dimension(2000, 1200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Hash function is k%15");

        Insert.setBackground(new java.awt.Color(97, 212, 195));
        Insert.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Insert.setForeground(new java.awt.Color(36, 47, 65));
        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        search_box_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        search_box_text.setToolTipText("");
        search_box_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_box_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_box_textFocusLost(evt);
            }
        });
        search_box_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_box_textActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Extendible Hashing");

        table.setBackground(new java.awt.Color(97, 212, 195));
        table.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        table.setForeground(new java.awt.Color(36, 47, 65));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Directory Number", "Bucket ID", "Local Depth", "Content of Bucket pointed by it"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.setEnabled(false);
        table.setGridColor(java.awt.Color.black);
        table.setRowHeight(30);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        global_depth.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        gd_input.setBackground(new java.awt.Color(97, 212, 195));
        gd_input.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gd_input.setForeground(new java.awt.Color(36, 47, 65));
        gd_input.setText("Enter GD");
        gd_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gd_inputActionPerformed(evt);
            }
        });

        BFR.setBackground(new java.awt.Color(97, 212, 195));
        BFR.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BFR.setForeground(new java.awt.Color(36, 47, 65));
        BFR.setText("Enter BFR");
        BFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFRActionPerformed(evt);
            }
        });

        bfr_input.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        searchbutton.setBackground(new java.awt.Color(97, 212, 195));
        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(36, 47, 65));
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        user_input1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        user_input1.setToolTipText("");
        user_input1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_input1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_input1FocusLost(evt);
            }
        });
        user_input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_input1ActionPerformed(evt);
            }
        });

        clear1.setBackground(new java.awt.Color(97, 212, 195));
        clear1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear1.setForeground(new java.awt.Color(36, 47, 65));
        clear1.setText("Clear");
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        clear2.setBackground(new java.awt.Color(97, 212, 195));
        clear2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear2.setForeground(new java.awt.Color(36, 47, 65));
        clear2.setText("Clear");
        clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2ActionPerformed(evt);
            }
        });

        clear4.setBackground(new java.awt.Color(97, 212, 195));
        clear4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear4.setForeground(new java.awt.Color(36, 47, 65));
        clear4.setText("Clear");
        clear4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear4ActionPerformed(evt);
            }
        });

        clear3.setBackground(new java.awt.Color(97, 212, 195));
        clear3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear3.setForeground(new java.awt.Color(36, 47, 65));
        clear3.setText("Clear");
        clear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear3ActionPerformed(evt);
            }
        });

        Restart.setBackground(new java.awt.Color(97, 212, 195));
        Restart.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Restart.setForeground(new java.awt.Color(36, 47, 65));
        Restart.setText("Restart");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userinputLayout = new javax.swing.GroupLayout(userinput);
        userinput.setLayout(userinputLayout);
        userinputLayout.setHorizontalGroup(
            userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinputLayout.createSequentialGroup()
                .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userinputLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1))
                    .addGroup(userinputLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userinputLayout.createSequentialGroup()
                                .addComponent(BFR, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(bfr_input, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(userinputLayout.createSequentialGroup()
                                .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userinputLayout.createSequentialGroup()
                                        .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(searchbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(gd_input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Insert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(122, 122, 122)
                                        .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(global_depth, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(user_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(search_box_text, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clear3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clear4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Restart, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userinputLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(325, 325, 325))
        );
        userinputLayout.setVerticalGroup(
            userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Restart, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(global_depth, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(clear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(gd_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BFR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clear2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bfr_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_box_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userinput, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(952, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userinput, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean ok = false;
    
   
    
    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        
   
           int value;
           
           
       if(b1 == false & !ok)
        {
            JOptionPane.showMessageDialog(null, "Enter BFR");
            b1=false;
            d1=false;
            return;
        }
        
        if(!(d1 == false & !ok))
        {
        } else {
            JOptionPane.showMessageDialog(null, "Enter Global Depth");
            b1=false;
            d1=false;
            return;
        }
        
        if(b1&d1 & (!ok))
        {
            d=new Directory(bfr,globaldepth);
            gd_input.setEnabled(false);
            BFR.setEnabled(false);
            ok = true;
            b1=false;
            d1=false;
        }
        

        try
        {
                 value = Integer.parseInt(user_input1.getText());
                 
                 if(store.contains(value))
                 {
                     JOptionPane.showMessageDialog(null, "Key Discarded \n Key Already Present");
                     return;
                 }
                 store.add(value);
                d.insert(value);


                ArrayList<Bucket> buckets = d.getBuckets();
                
                HashMap<Integer,Integer> index = d.getIndex();
                
                int len = (int) Math.pow(2, d.getDepth());
                for(int i = 0; i < len; i++)
                {
                    String str = Integer.toBinaryString(BitUtility.getRightMostBits(i,d.getDepth()));
                 StringBuilder sb = new StringBuilder();

                   for (int toPrepend=d.getDepth()-str.length(); toPrepend>0; toPrepend--)  sb.append('0');
                   
                 sb.append(str);
                  str = sb.toString();
                  
                   table.setValueAt((Object)(str),i,0);
                   
                    if(index.get(i) != -1)
                    {
                        Bucket b = buckets.get(index.get(i));
                        table.setValueAt((Object)(b.id),i,1);
                        table.setValueAt((Object)(b.getLocalDepth()),i,2);
                        table.setValueAt((Object)(b.print()),i,3);
                    }
                }
            
        
        
        }
        catch( NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter an integer");
        }
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertActionPerformed

    private void search_box_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_box_textFocusGained
        // TODO add your handling code here:
        if(search_box_text.getText().equals("Enter Integer")){
            search_box_text.setText(null);
            search_box_text.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_search_box_textFocusGained

    private void search_box_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_box_textFocusLost
        // TODO add your handling code here:
        if(search_box_text.getText().equals("")){
            search_box_text.setForeground(new Color(204,204,204));
            search_box_text.setText("Enter Integer");
        }
    }//GEN-LAST:event_search_box_textFocusLost

    private void search_box_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_box_textActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_search_box_textActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void gd_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gd_inputActionPerformed
        // TODO add your handling code here:
          try
        {
        globaldepth = Integer.parseInt(global_depth.getText());
        d1=true;
        }
      catch( NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter an integer");
        }
          
//d = new Directory(3,val);
    }//GEN-LAST:event_gd_inputActionPerformed

    private void BFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFRActionPerformed
        // TODO add your handling code here:
        try
        {
        bfr = Integer.parseInt(bfr_input.getText());
        b1=true;
        }
       catch( NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter an integer");
        }
//d = new Directory(val,gd);
    }//GEN-LAST:event_BFRActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
        
        
      int value_to_search;
      
          try
        {
            value_to_search = Integer.parseInt(search_box_text.getText());
            if(search_box_text.getText() == "")
            {
                  JOptionPane.showMessageDialog(null, "Enter an integer");
            return;
            }
        

        }
      catch( NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter an integer");
            return;
        }
          
        if(store.contains(value_to_search) == false)
        {
            JOptionPane.showMessageDialog(null, "NOT FOUND");
            return;
        }
         JOptionPane.showMessageDialog(null, d.search(value_to_search));
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void user_input1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_input1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_user_input1FocusGained

    private void user_input1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_input1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_user_input1FocusLost

    private void user_input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_input1ActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        // TODO add your handling code here:
        
        global_depth.setText("");
    }//GEN-LAST:event_clear1ActionPerformed

    private void clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2ActionPerformed
        // TODO add your handling code here:
        bfr_input.setText("");
    }//GEN-LAST:event_clear2ActionPerformed

    private void clear4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear4ActionPerformed
        // TODO add your handling code here:
        search_box_text.setText("");
    }//GEN-LAST:event_clear4ActionPerformed

    private void clear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear3ActionPerformed
        // TODO add your handling code here:
        
        user_input1.setText("");
        
    }//GEN-LAST:event_clear3ActionPerformed

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUI().setVisible(true);
    }//GEN-LAST:event_RestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BFR;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Restart;
    private javax.swing.JTextField bfr_input;
    private javax.swing.JButton clear1;
    private javax.swing.JButton clear2;
    private javax.swing.JButton clear3;
    private javax.swing.JButton clear4;
    private javax.swing.JButton gd_input;
    private javax.swing.JTextField global_depth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search_box_text;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTable table;
    private javax.swing.JTextField user_input1;
    private javax.swing.JPanel userinput;
    // End of variables declaration//GEN-END:variables
}
